alias: Create notifications for "service" errors
trigger:
  platform: event
  event_type: system_log_event
condition:
  condition: template
  value_template: '{{ "service" in trigger.event.data.message }}'
action:
  service: persistent_notification.create
  data_template:
    title: Something bad happened
    message: '{{ trigger.event.data.message }}'
