alias: "IFTTT webhook for moisture"
trigger:
  platform: event
  event_type: ifttt_webhook_received
  event_data:
    action: call_service
action:
  service: notify.ios_jay_iphone
  data_template:
    title: "Moisture detected"
    message: "Moisture detected {{ trigger.event.data.DeviceName }} and {{ trigger.event.moisture_detected_at }}"